<?php
function custom_ferramentas() {
	$labels = array(
		'name'                  => _x( 'Ferramentas', 'Post Type General Name', 'text_domain' ),
		'singular_name'         => _x( 'Ferramenta', 'Post Type Singular Name', 'text_domain' ),
		'menu_name'             => __( 'Ferramentas', 'text_domain' ),
		'name_admin_bar'        => __( 'Ferramentas', 'text_domain' ),
		'archives'              => __( 'Ferramentas Arquivados', 'text_domain' ),
		'parent_item_colon'     => __( 'Item pai:', 'text_domain' ),
		'all_items'             => __( 'Todos os Ferramentas', 'text_domain' ),
		'add_new_item'          => __( 'Adicionar novo Ferramenta', 'text_domain' ),
		'add_new'               => __( 'Adicionar novo', 'text_domain' ),
		'new_item'              => __( 'Novo Ferramenta', 'text_domain' ),
		'edit_item'             => __( 'Editar Ferramenta', 'text_domain' ),
		'update_item'           => __( 'Atualizar Ferramenta', 'text_domain' ),
		'view_item'             => __( 'Ver Ferramenta', 'text_domain' ),
		'search_items'          => __( 'Buscar Ferramenta', 'text_domain' ),
		'not_found'             => __( 'Nenhum cadastrado', 'text_domain' ),
		'not_found_in_trash'    => __( 'Nenhum na lixeira', 'text_domain' ),
		'featured_image'        => __( 'Imagem destaque', 'text_domain' ),
		'set_featured_image'    => __( 'Definir imagem', 'text_domain' ),
		'remove_featured_image' => __( 'Remover imagem', 'text_domain' ),
		'use_featured_image'    => __( 'Usar imagem Ferramenta', 'text_domain' ),
		'insert_into_item'      => __( 'Inserir no Ferramenta', 'text_domain' ),
		'uploaded_to_this_item' => __( 'Subir para Ferramenta', 'text_domain' ),
		'items_list'            => __( 'Lista de Ferramentas', 'text_domain' ),
		'items_list_navigation' => __( 'Navegar pelos Ferramentas', 'text_domain' ),
		'filter_items_list'     => __( 'Filtrar Ferramentas', 'text_domain' ),
	);
	$args = array(
		'label'                 => __( 'Ferramentas', 'text_domain' ),
		'description'           => __( 'Cadastrar Ferramenta', 'text_domain' ),
		'labels'                => $labels,
		'supports'              => array( 'title', ),
		// 'taxonomies'            => array( 'categoria_Ferramentas' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		"show_in_rest"			=> true,
		'menu_position'         => 5,
		'menu_icon'				=> 'dashicons-hammer',		
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => true,		
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'capability_type'       => 'page',
	);
	register_post_type( 'ferramentas', $args );
}
add_action( 'init', 'custom_ferramentas', 0 );
